services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ai-interviewer-db
    environment:
      POSTGRES_DB: ai_interviewer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ai-interviewer-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend FastAPI
  backend:
    build:
      context: ./backend_fastapi
      dockerfile: Dockerfile
    container_name: ai-interviewer-backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/ai_interviewer
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
      ENVIRONMENT: production
    volumes:
      - ./backend_fastapi:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ai-interviewer-network
    command: >
      sh -c "
        prisma generate &&
        prisma migrate deploy &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-interviewer-frontend
    environment:
      VITE_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - ai-interviewer-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  ai-interviewer-network:
    driver: bridge
